//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkActivity
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string OfficeName { get; set; }
        public int UserCount { get; set; }
    }
}
