//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCCMWindowsServer
    {
        public int ID { get; set; }
        public string SID { get; set; }
        public string Hostname { get; set; }
        public string OperatingSystem { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public string AVVersion { get; set; }
        public string AVSignatureVersion { get; set; }
        public Nullable<System.DateTime> AVSignatureUpdate { get; set; }
        public Nullable<System.DateTime> AVLastScan { get; set; }
        public string AVInfectionStatus { get; set; }
        public string SoftwareUpdateStatus { get; set; }
        public string SoftwareUpdateStatusBasic { get; set; }
        public Nullable<System.DateTime> LastBootUpTime { get; set; }
        public string MaintenanceGroup { get; set; }
        public string MaintenanceWindow { get; set; }
        public string Environment { get; set; }
    }
}
