//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string GUID { get; set; }
        public string SID { get; set; }
        public string WorkdayID { get; set; }
        public string EmployeeType { get; set; }
        public string Country { get; set; }
        public string Area { get; set; }
        public string Office { get; set; }
        public string Department { get; set; }
        public string Title { get; set; }
        public string ManagersName { get; set; }
        public string ManagersEmail { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public Nullable<int> Age { get; set; }
        public string AgeRange { get; set; }
        public Nullable<int> YOS { get; set; }
        public string YOSRange { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<bool> LeadershipForum { get; set; }
        public Nullable<bool> Technical { get; set; }
    }
}
